
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="fade-in h-screen bg-slate-100">
       

          {children}
        

     
        
        
        
        
        </body>
    </html>
  );
}
